1| 
2| const currentYear = new Date().getFullYear();
3| export const content = {
4|   en: {
5|     meta: {
6|       title: "Uttarpara Amarendra Vidyapith - Reunion Hub (1988 & 1990 Batches)",
7|       description: "Join the reunion for the 1988 Madhyamik & 1990 HS batches of Uttarpara Amarendra Vidyapith.",
8|     },
9|     nav: {
10|       title: "Reunion Hub",
11|       register: "Register",
12|       details: "Details",
13|       program: "Program",
14|       menu: "Menu",
15|       attendees: "Attendees",
16|       icebreaker: "Icebreaker",
17|       faq: "FAQ",
18|       translate: "বাংলা",
19|     },
20|     hero: {
21|       title: "Welcome, Alumni of Uttarpara Amarendra Vidyapith!",
22|       subtitle: "Reconnect with friends from the 1988 Madhyamik and 1990 HS batches. Let's reminisce and make new memories at our grand school reunion.",
23|       imageAlt: "Uttarpara Amarendra Vidyapith school building",
24|     },
25|     reunionDetails: {
26|       cardTitle: "You're Invited!",
27|       eventName: "Uttarpara Amarendra Vidyapith - Grand Reunion (1988 Madhyamik & 1990 HS)",
28|       dateLabel: "Date",
29|       date: "Saturday, 6th December, 2025",
30|       timeLabel: "Time",
31|       time: "10:00 AM - 9:00 PM",
32|       venueLabel: "Venue",
33|       venue: "Bhorer Alo Community Hall, Uttarpara, West Bengal, India",
34|     },
35|     programSchedule: {
36|       title: "Program Schedule",
37|       description: "A day full of nostalgia, fun, and reconnecting after 35 years.",
38|       schedule: [
39|         { time: "9:00-9:30 AM", title: "Welcome Tea/Coffee/Soft Drinks", description: "Start the day with a refreshing drink and warm greetings." },
40|         { time: "9:30-10:30 AM", title: "Breakfast", description: "Enjoy a hearty breakfast and catch up with old friends." },
41|         { time: "10:30-11:30 AM", title: "Introduction / Back to School", description: "Share memories and stories from our school days." },
42|         { time: "11:30-12:00 PM", title: "Health Check Up", description: "A quick health check-up session for everyone." },
43|         { time: "12:00-1:30 PM", title: "Future Planning / Discussion", description: "Let's discuss our future plans and how we can stay connected." },
44|         { time: "1:30-3:00 PM", title: "Lunch", description: "A delicious lunch to refuel for the rest of the day's activities." },
45|         { time: "3:00-4:30 PM", title: "Stage Performance / Karaoke / Jokes etc.", description: "Showcase your talents or just enjoy the performances." },
46|         { time: "4:30-5:00 PM", title: "Tea/Coffee", description: "A short break for tea and coffee." },
47|         { time: "5:00-6:00 PM", title: "Performance / Karaoke / Jokes etc.", description: "The fun continues with more performances and entertainment." },
48|         { time: "6:00-6:30 PM", title: "Evening Snacks", description: "Light snacks to keep the energy levels high." },
49|         { time: "6:30-8:30 PM", title: "Party", description: "Let's celebrate our reunion with music and dance." },
50|         { time: "8:30-9:30 PM", title: "Dinner", description: "End the day with a grand dinner and fond farewells." }
51|       ],
52|     },
53|     registrationForm: {
54|       title: "Register for the Reunion",
55|       description: "Fill out the form below to confirm your attendance. Some fields are just for fun!",
56|       nameLabel: "Name",
57|       presentAddressLabel: "Present Address",
58|       permanentAddressLabel: "Permanent Address",
59|       mobileLabel: "Mobile No.",
60|       emailLabel: "Email Address",
61|       bloodGroupLabel: "Blood Group",
62|       professionLabel: "Profession",
63|       jobNatureLabel: "Nature of Job",
64|       organizationLabel: "Name of Organization",
65|       maritalStatusLabel: "Marital Status",
66|       girlfriendsLabel: "No. of girlfriends",
67|       wardsOfficialLabel: "No. of ward (official)",
68|       wardsUnofficialLabel: "No. of ward (unofficial)",
69|       testosteroneLabel: "Level of testosterone",
70|       remarksLabel: "Remarks",
71|       submitButton: "Register Now"
72|     },
73|     menuSection: {
74| 
75|     title: "Dr. Pradip Dey Menu Lab 🧑‍🔬",
76|     description: "Shh! The menu is a delicious secret. Come hungry, leave happy! 🍴✨",
77|     breakfast: {
78|       title: "জলখাবার (JALKHABAR) 🌅",
79|       jokes: [
80|         "Breakfast curated by Dr. Pradip Dey — guaranteed 100% farm-fresh and 200% confusion.",
81|         "Morning menu by Pradi… if anything sprouts on your plate, that's part of the plan.",
82|         "Our scientist-in-charge says breakfast will be high-yield… for our stomachs.",
83|         "Pradi's breakfast: scientifically proven to wake you up, whether you want or not.",
84|         "Don't worry, breakfast is pesticide-free. The jokes aren't.",
85|         "প্রদীপবাবুর সকালের মেনু — ১০০% তাজা ফসল আর ২০০% বিভ্রান্তি গ্যারান্টিড�[...]",
86|         "সকালের খাবার প্রদীপ দার তত্ত্বাবধানে... প্লেটে কিছু গজালে সেটাই পরিকল্�[...]",
87|         "আমাদের বিজ্ঞানী বলছেন সকালের খাবার high-yield হবে... পেটের জন্য।",
88|         "প্রদীপবাবুর ব্রেকফাস্ট: বৈজ্ঞানিকভাবে প্রমাণিত জাগিয়ে তুলবে, চান বা [...]",
89|         "চিন্তা নেই, সকালের খাবার pesticide-free। কৌতুক অবশ্য নয়।"
90|       ]
91|     },
92|     lunch: {
93|       title: "LUNCH 🌞",
94|       jokes: [
95|         "Lunch by Dr. Dey — optimized for maximum photosynthesis after eating.",
96|         "Today's lunch is research grade. Please don't ask for peer review.",
97|         "Pradi promises lunch that increases productivity… at least of burps.",
98|         "If lunch feels like a field experiment, remember: we are the sample size.",
99|         "Lunch menu so secret, even the agricultural department needs clearance.",
100|         "দুপুরের খাবার ডক্টর দে-র তত্ত্বাবধানে — খাওয়ার পর সর্বোচ্চ photosynthesis নিশ্[...]",
101|         "আজকের লাঞ্চ research grade। peer review চাইবেন না please।",
102|         "প্রদীপবাবু প্রতিশ্রুতি দিচ্ছেন লাঞ্চ productivity বাড়াবে... অন্তত ঢেঁকুরের।",
103|         "লাঞ্চ যদি field experiment মনে হয়, মনে রাখবেন: আমরাই sample size।",
104|         "লাঞ্চ মেনু এতটাই গোপন, কৃষি বিভাগেরও clearance লাগে।"
105|       ]
106|     },
107|     evening: {
108|       title: "TIFFIN (EVENING) 🌥",
109|       jokes: [
110|         "Evening tiffin curated by Dr. Dey — perfect for those who like snacks with scientific uncertainty.",
111|         "Tiffin so fresh, he might still be monitoring its soil moisture.",
112|         "Pradi's tiffin: ideal for those who believe snacks should also undergo field trials.",
113|         "If your tiffin crunches strangely… that's texture optimization, not a mistake.",
114|         "Tiffin strictly based on agricultural principles: zero wastage, maximum munchage.",
115|         "সন্ধ্যার টিফিন ডক্টর দে-র তত্ত্বাবধানে — যারা বৈজ্ঞানিক অনিশ্চয়তা স��[...]",
116|         "টিফিন এতটাই তাজা, উনি হয়তো এখনও soil moisture মনিটর করছেন।",
117|         "প্রদীপবাবুর টিফিন: যারা বিশ্বাস করেন স্ন্যাকসেরও field trial হওয়া উচিত তাদে[...]",
118|         "টিফিন যদি অদ্ভুতভাবে কচকচ করে... সেটা texture optimization, ভুল নয়।",
119|         "টিফিন সম্পূর্ণ কৃষি নীতি অনুযায়ী: শূন্য অপচয়, সর্বোচ্চ munchage।"
120|       ]
121|     },
122|     dinner: {
123|       title: "DINNER 🌙",
124|       jokes: [
125|         "Dinner designed by our scientist — expect high nutrition, low nonsense… or maybe reverse.",
126|         "Pradi's dinner: cultivated with love, served with scientific overconfidence.",
127|         "Dinner may or may not follow crop rotation principles. Eat responsibly.",
128|         "If dinner tastes experimental… congratulations, you're participating in innovation.",
129|         "Night menu curated by Dr. Dey — the only scientist who can turn dinner into a seminar.",
130|         "রাতের খাবার আমাদের বিজ্ঞানীর ডিজাইন — আশা করুন উচ্চ পুষ্টি, কম বাজে কথ��[...]",
131|         "প্রদীপবাবুর রাতের খাবার: ভালোবাসা দিয়ে চাষ, বৈজ্ঞানিক আত্মবিশ্বাসে ��[...]",
132|         "ডিনার হয়তো crop rotation নীতি মানে, নাও মানতে পারে। দায়িত্বশীলভাবে খান।",
133|         "ডিনার যদি পরীক্ষামূলক লাগে... অভিনন্দন, আপনি innovation-এ অংশগ্রহণ করছেন।",
134|         "রাতের মেনু ডক্টর দে-র তত্ত্বাবধানে — একমাত্র বিজ্ঞানী যিনি ডিনারকে সে�[...]"
135|       ]
136|     }
137|         },
138|   
139|     },
140|     confirmedAttendees: {
141|       title: "Confirmed Attendees",
142|       description: "Here's who has already confirmed their presence.",
143|       addMorePrompt: "Want to add a name to the list?",
144|       namePlaceholder: "Enter a name...",
145|       addButton: "Add",
146|       addSuccessToastTitle: "Name Added!",
147|       addSuccessToastDescription: "has been added to the list.",
148|       names: [
149|         "Tanmoy", "Basab", "Sekharjit", "Supratim", "Chandan", 
150|         "Biswaranjan", "Pradip", "Yogabrata", "Sudipta", "Shovon", "Arun", 
151|         "Srikanta", "Amal", "Samir Mondal", "Subrata", "Sujoy", "Samar", 
152|         "Uttam", "Chiranjeeb", "Siddhartha", "Anirban", "Mridul", "Swarup", 
153|         "Sanjay Banik"
154|       ]
155|     },
156|     icebreakerTool: {
157|       title: "Icebreaker Corner",
158|       description: "Want to start a conversation? Enter some details (real or imaginary) to get a personalized question!",
159|       nameLabel: "Attendee Name",
160|       namePlaceholder: "e.g., Alex Smith",
161|       phoneLabel: "Attendee Phone (Optional)",
162|       phonePlaceholder: "e.g., +19876543210",
163|       fishLabel: "Prefers Fish Dishes?",
164|       alcoholicLabel: "Prefers Alcoholic Drinks?",
165|       submitButton: "Get an Icebreaker Question",
166|       submittingButton: "Generating...",
167|       suggestionTitle: "Your Icebreaker:",
168|       successToastTitle: "Question Generated!",
169|       successToastDescription: "Here's a fun question to get the conversation started.",
170|       failureToastTitle: "Generation Failed",
171|       failureToastDescription: "Couldn't generate a question.",
172|       errorToastTitle: "Error",
173|       errorToastDescription: "Something went wrong. Please try again.",
174|       disabledTitle: "Feature Disabled",
175|       disabledDescription: "The AI Icebreaker tool is available in the local development environment but is disabled in the deployed version.",
176|     },
177|     faq: {
178|       title: "Frequently Asked Questions",
179|       description: "Find answers to common questions about the reunion.",
180|       faqs: [
181|         {
182|           id: "faq-1",
183|           question: "What is the dress code for the reunion?",
184|           answer: "The dress code is smart casual. Feel free to dress comfortably and stylishly for a day of fun and reconnection!",
185|         },
186|         {
187|           id: "faq-2",
188|           question: "Can I bring a guest to the reunion?",
189|           answer: "Due to venue constraints and planning, registration is primarily for alumni. If you wish to bring a guest, please contact the organizers in advance to check for availability.",
190|         },
191|         {
192|           id: "faq-3",
193|           question: "Is there parking available at the venue?",
194|           answer: "Limited parking is available at the venue. We encourage carpooling or using public transport if possible to ease congestion.",
195|         },
196|         {
197|           id: "faq-5",
198|           question: "Will food and beverages be provided?",
199|           answer: "Yes! A variety of delicious food and refreshing beverages will be provided throughout the event from 10 AM to 9 PM. We will have options to cater to different tastes.",
200|         },
201|       ],
202|     },
203|     footer: {
204|       copyright: `© ${currentYear} Reunion Hub. All rights reserved.`,
205|       closing: "Looking forward to celebrating with you!",
206|     },
207|   },
208|   bn: {
209|     meta: {
210|       title: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ - পুনর্মিলন হাব (১৯৮৮ ও ১৯৯০ ব্যাচ)",
211|       description: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠের ১৯৮৮ মাধ্যমিক এবং ১৯৯০ উচ্চ মাধ��[...]",
212|     },
213|     nav: {
214|       title: "পুনর্মিলন কেন্দ্র",
215|       register: "নিবন্ধন",
216|       details: "বিবরণ",
217|       program: "অনুসূচী",
218|       menu: "খাদ্যতালিকা",
219|       attendees: "উপস্থিতি",
220|       icebreaker: "পরিচিতি পর্ব",
221|       faq: "প্রশ্নাবলী",
222|       translate: "English",
223|     },
224|     hero: {
225|       title: "স্বাগতম, উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠের প্রাক্তন ছাত্র-ছাত্রীরা[...]",
226|       subtitle: "১৯৮৮ মাধ্যমিক ও ১৯৯০ উচ্চ মাধ্যমিক ব্যাচের বন্ধুদের সাথে আবার আয়, আ�[...]",
227|       imageAlt: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ স্কুল ভবন",
228|     },
229|     reunionDetails: {
230|       cardTitle: "আসলে কেউ বড় হয় না",
231|       eventName: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ - মহা পুনর্মিলন (১৯৮৮ মাধ্যমিক ও ১৯৯০ উচ্চ মাধ্যমিক)",
232|       dateLabel: "তারিখ",
233|       date: "শনিবার, ৬ই ডিসেম্বর, ২০২৫",
234|       timeLabel: "সময়",
235|       time: "সকাল ৯:০০ - রাত ৯:০০",
236|       venueLabel: "স্থান",
237|       venue: "ভোরের আলো কমিউনিটি হল, উত্তরপাড়া, পশ্চিমবঙ্গ, ভারত",
238|     },
239|     programSchedule: {
240|       title: "অনুষ্ঠানসূচী",
241|       description: "৩৫ বছর পর স্মৃতিচারণ, মজা এবং পুনর্মিলনে ভরা একটা দিন।",
242|       schedule: [
243|         { time: "সকাল ৯:০০-৯:৩০", title: "স্বাগত চা/কফি/সফট ড্রিঙ্কস", description: "একটি সতেজ পানীয় �[...]"},
244|         { time: "সকাল ৯:৩০-১০:৩০", title: "প্রাতঃরাশ", description: "হৃদয়গ্রাহী ব্রেকফাস্ট উপভোগ ক��[...]"},
245|         { time: "সকাল ৯:৩০-১১:৩০", title: "পরিচিতি পর্ব / স্কুলে ফেরা", description: "আমাদের স্কুলের দ�[...]"},
246|         { time: "সকাল ১১:৩০-দুপুর ১২:০০", title: "স্বাস্থ্য পরীক্ষা", description: "সকলের জন্য একটি দ[...]"},
247|         { time: "দুপুর ১২:০০-১:৩০", title: "ভবিষ্যৎ পরিকল্পনা / আলোচনা", description: "আসুন আমাদের ভব��[...]"},
248|         { time: "দুপুর ১:৩০-৩:০০", title: "মধ্যাহ্নভোজ", description: "দিনের বাকি কার্যকলাপের জন্য প�[...]"},
249|         { time: "বিকেল ৩:০০-৪:৩০", title: "মঞ্চে পারফরম্যান্স / কারাওকে / জোকস ইত্যাদি", description: "[...]"},
250|         { time: "বিকেল ৪:৩০-৫:০০", title: "চা/কফি", description: "চা এবং কফির জন্য একটি সংক্ষিপ্ত বিরত�[...]"},
251|         { time: "বিকেল ৫:০০-৬:০০", title: "পারফরম্যান্স / কারাওকে / জোকস ইত্যাদি", description: "মজা আর[...]"},
252|         { time: "সন্ধ্যা ৬:০০-৬:৩০", title: "সান্ধ্যকালীন জলখাবার", description: "শক্তির মাত্রা উচ्��[...]"},
253|         { time: "সন্ধ্যা ৬:৩০-৮:৩০", title: "পার্টি", description: "আসুন সঙ্গীত এবং নৃত্যের সাথে আমাদ[...]"},
254|         { time: "রাত ৮:৩০-৯:৩০", title: "রাতের খাবার", description: "একটি भব্য ডিনার এবং স্নেহপূর্ণ ব��[...]"}
255|       ],
256|     },
257|     registrationForm: {
258|       title: "পুনর্মিলনের জন্য নিবন্ধন করুন",
259|       description: "আপনার উপস্থিতি নিশ্চিত করতে নীচের ফর্মটি পূরণ করুন। কিছু ক্ষেত্র [...]",
260|       nameLabel: "নাম",
261|       presentAddressLabel: "বর্তমান ঠিকানা",
262|       permanentAddressLabel: "স্থায়ী ঠিকানা",
263|       mobileLabel: "মোবাইল নম্বর",
264|       emailLabel: "ইমেল ঠিকানা",
265|       bloodGroupLabel: "রক্তের গ্রুপ",
266|       professionLabel: "পেশা",
267|       jobNatureLabel: "কাজের ধরণ",
268|       organizationLabel: "প্রতিষ্ঠানের নাম",
269|       maritalStatusLabel: "বৈবাহিক অবস্থা",
270|       girlfriendsLabel: "গার্লফ্রেন্ডের সংখ্যা",
271|       wardsOfficialLabel: "সন্তানের সংখ্যা (অফিসিয়াল)",
272|       wardsUnofficialLabel: "সন্তানের সংখ্যা (অনানুষ্ঠানিক)",
273|       testosteroneLabel: "টেস্টোস্টেরনের মাত্রা",
274|       remarksLabel: "মন্তব্য",
275|       submitButton: "এখন নিবন্ধন করুন"
276|     },
277|     confirmedAttendees: {
278|       title: "যারা ইতিমধ্যে কনফার্ম করেছে:",
279|       description: "যারা ইতিমধ্যে তাদের উপস্থিতি নিশ্চিত করেছে তাদের তালিকা নিচে দেও�[...]",
280|       addMorePrompt: "তালিকায় একটি নাম যোগ করতে চান?",
281|       namePlaceholder: "একটি নাম লিখুন...",
282|       addButton: "যোগ করুন",
283|       addSuccessToastTitle: "নাম যোগ করা হয়েছে!",
284|       addSuccessToastDescription: "তালিকায় যোগ করা হয়েছে।",
285|       names: [
286|         "তন্ময়", "বাসব", "রাতুল", "শেখরজিৎ", "সুপ্রতিম", "চন্দন", 
287|         "বিশ্বরঞ্জন", "প্রদীপ", "যোগব্রত", "সুদীপ্ত", "শোভন", "অরুণ", 
288|         "শ্রীকান্ত", "অমল", "সমীর মন্ডল", "সুব্রত", "সুজয়", "সমর", 
289|         "উত্তম", "চিরঞ্জীব", "সিদ্ধার্থ", "অনির্বাণ", "মৃদুল", "স্বরূপ", 
290|         "সঞ্জয় বণিক"
291|       ]
292|     },
293|     icebreakerTool: {
294|       title: "পরিচিতি পর্ব",
295|       description: "কথাবার্তা শুরু করতে চান? একটি ব্যক্তিগতকৃত প্রশ্ন পেতে কিছু (কাল্��[...]",
296|       nameLabel: "অংশগ্রহণকারীর নাম",
297|       namePlaceholder: "যেমনঃ আকাশ সেন",
298|       phoneLabel: "অংশগ্রহণকারীর ফোন (ঐচ্ছিক)",
299|       phonePlaceholder: "যেমনঃ +৮৮০১২৩৪৫৬৭৮৯০",
300|       fishLabel: "মাছের পদ পছন্দ করেন?",
301|       alcoholicLabel: "অ্যালকোহলযুক্ত পানীয় পছন্দ করেন?",
302|       submitButton: "আলোচনা শুরু করার প্রশ্ন পান",
303|       submittingButton: "তৈরি হচ্ছে...",
304|       suggestionTitle: "আপনার জন্য প্রশ্ন:",
305|       successToastTitle: "প্রশ্ন তৈরি!",
306|       successToastDescription: "কথাবার্তা শুরু করার জন্য এখানে একটি মজার প্রশ্ন রয়েছে।",
307|       failureToastTitle: "তৈরি করতে ব্যর্থ",
308|       failureToastDescription: "একটি প্রশ্ন তৈরি করা যেতে পারেনি।",
309|       errorToastTitle: "ত্রুটি",
310|       errorToastDescription: "কিছু একটা সমস্যা হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
311|       disabledTitle: "বৈশিষ্ট্য নিষ্ক্রিয়",
312|       disabledDescription: "এআই আইসব্রেকার টুলটি স্থানীয় ডেভেলপমেন্ট পরিবেশে উপলব্ধ কিন�[...]",
313|     },
314|     faq: {
315|       title: "সচরাচর জিজ্ঞাসিত প্রশ্ন",
316|       description: "পুনর্মিলন সম্পর্কিত সাধারণ প্রশ্নের উত্তর খুঁজুন।",
317|       faqs: [
318|         {
319|           id: "faq-1",
320|           question: "পুনর্মিলনের জন্য পোশাক বিধি কী?",
321|           answer: "পোশাক বিধি হলো স্মার্ট ক্যাজুয়াল। আনন্দ এবং পুনর্মিলনের একটি দি��[...]",
322|         },
323|         {
324|           id: "faq-2",
325|           question: "আমি কি পুনর্মিলনীতে অতিথি আনতে পারি?",
326|           answer: "স্থানের সীমাবদ্ধতা এবং পরিকল্পনার কারণে, নিবন্ধন প্রাথমিকভাবে প্[...]",
327|         },
328|         {
329|           id: "faq-3",
330|           question: "অনুষ্ঠানস্থলে কি পার্কিংয়ের ব্যবস্থা আছে?",
331|           answer: "অনুষ্ঠানস্থলে সীমিত পার্কিং উপলব্ধ। যানজট কমাতে আমরা সম্ভব হলে ক��[...]",
332|         },
333|         {
334|           id: "faq-5",
335|           question: "খাবার ও পানীয় কি সরবরাহ করা হবে?",
336|           answer: "হ্যাঁ! সকাল ৯টা থেকে রাত ৯টা পর্যন্ত অনুষ্ঠান জুড়ে বিভিন্ন ধরনের ��[...]",
337|         },
338|       ],
339|     },
340|     footer: {
341|       copyright: `© ${currentYear} পুনর্মিলন কেন্দ্র। সর্বস্বত্ব সংরক্ষিত।`,
342|       closing: "তোমাদের সাথে উদযাপন করার জন্য উন্মুখ!",
343|     },
344|   },
345| };