
export const content = {
  en: {
    meta: {
      title: "Uttarpara Amarendra Vidyapith - Reunion Hub (1988 & 1990 Batches)",
      description: "Join the reunion for the 1988 Madhyamik & 1990 HS batches of Uttarpara Amarendra Vidyapith.",
    },
    nav: {
      title: "Reunion Hub",
      details: "Details",
      register: "Register",
      icebreaker: "Icebreaker",
      faq: "FAQ",
      translate: "বাংলা",
    },
    hero: {
      title: "Welcome, Alumni of Uttarpara Amarendra Vidyapith!",
      subtitle: "Reconnect with friends from the 1988 Madhyamik and 1990 HS batches. Let's reminisce and make new memories at our grand school reunion.",
      imageAlt: "Uttarpara Amarendra Vidyapith school building",
    },
    reunionDetails: {
      cardTitle: "You're Invited!",
      eventName: "Uttarpara Amarendra Vidyapith - Grand Reunion (1988 Madhyamik & 1990 HS)",
      dateLabel: "Date",
      date: "Saturday, 6th December, 2025",
      timeLabel: "Time",
      time: "10:00 AM - 9:00 PM",
      venueLabel: "Venue",
      venue: "'Alo Ghor', Uttarpara, West Bengal, India",
    },
    registrationForm: {
      title: "Register for the Reunion",
      description: "Secure your spot and let us know your t-shirt size!",
      nameLabel: "Full Name",
      namePlaceholder: "e.g., John Doe",
      phoneLabel: "Phone Number",
      phonePlaceholder: "e.g., +1234567890",
      tshirtLabel: "T-Shirt Size",
      tshirtPlaceholder: "Select your t-shirt size",
      submitButton: "Register Now",
      submittingButton: "Submitting...",
      successToastTitle: "Registration Successful!",
      failureToastTitle: "Registration Failed",
      errorToastTitle: "Error",
      errorToastDescription: "Something went wrong. Please try again.",
    },
    icebreakerTool: {
      title: "Icebreaker Corner",
      description: "Want to start a conversation? Enter some details (real or imaginary) to get a personalized question!",
      nameLabel: "Attendee Name",
      namePlaceholder: "e.g., Alex Smith",
      phoneLabel: "Attendee Phone (Optional)",
      phonePlaceholder: "e.g., +19876543210",
      tshirtLabel: "Attendee T-Shirt Size",
      tshirtPlaceholder: "Select a T-Shirt size",
      submitButton: "Get an Icebreaker Question",
      submittingButton: "Generating...",
      suggestionTitle: "Your Icebreaker:",
      successToastTitle: "Question Generated!",
      successToastDescription: "Here's a fun question to get the conversation started.",
      failureToastTitle: "Generation Failed",
      failureToastDescription: "Couldn't generate a question.",
      errorToastTitle: "Error",
      errorToastDescription: "Something went wrong. Please try again.",
    },
    faq: {
      title: "Frequently Asked Questions",
      description: "Find answers to common questions about the reunion.",
      faqs: [
        {
          id: "faq-1",
          question: "What is the dress code for the reunion?",
          answer: "The dress code is smart casual. Feel free to dress comfortably and stylishly for a day of fun and reconnection!",
        },
        {
          id: "faq-2",
          question: "Can I bring a guest to the reunion?",
          answer: "Due to venue constraints and planning, registration is primarily for alumni. If you wish to bring a guest, please contact the organizers in advance to check for availability.",
        },
        {
          id: "faq-3",
          question: "Is there parking available at the venue?",
          answer: "Limited parking is available at 'Alo Ghor'. We encourage carpooling or using public transport if possible to ease congestion.",
        },
        {
          id: "faq-4",
          question: "What are the COVID-19 safety protocols?",
          answer: "We will adhere to all local health guidelines and advisories at the time of the event. We kindly request that if you feel unwell, please stay home to ensure everyone's safety. Hand sanitizers will be available.",
        },
        {
          id: "faq-5",
          question: "Will food and beverages be provided?",
          answer: "Yes! A variety of delicious food and refreshing beverages will be provided throughout the event from 10 AM to 9 PM. We will have options to cater to different tastes.",
        },
      ],
    },
    footer: {
      copyright: `© ${new Date().getFullYear()} Reunion Hub. All rights reserved.`,
      closing: "Looking forward to celebrating with you!",
    },
  },
  bn: {
    meta: {
      title: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ - পুনর্মিলন হাব (১৯৮৮ ও ১৯৯০ ব্যাচ)",
      description: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠের ১৯৮৮ মাধ্যমিক এবং ১৯৯০ উচ্চ মাধ্যমিক ব্যাচের পুনর্মিলনে যোগ দিন।",
    },
    nav: {
      title: "পুনর্মিলন কেন্দ্র",
      details: "বিবরণ",
      register: "নিবন্ধন",
      icebreaker: "পরিচিতি পর্ব",
      faq: "প্রশ্নাবলী",
      translate: "English",
    },
    hero: {
      title: "স্বাগতম, উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠের প্রাক্তন ছাত্র-ছাত্রীরা!",
      subtitle: "১৯৮৮ মাধ্যমিক ও ১৯৯০ উচ্চ মাধ্যমিক ব্যাচের বন্ধুদের সাথে আবার আয়, আড্ডা দি। চল্, আমাদের এই স্কুল পুনর্মিলনীতে পুরনো স্মৃতিগুলো ঝালিয়ে নিই আর নতুন কিছু স্মৃতি তৈরি করি।",
      imageAlt: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ স্কুল ভবন",
    },
    reunionDetails: {
      cardTitle: "আসলে কেউ বড় হয় না",
      eventName: "উত্তরপাড়া অমরেন্দ্র বিদ্যাপীঠ - মহা পুনর্মিলন (১৯৮৮ মাধ্যমিক ও ১৯৯০ উচ্চ মাধ্যমিক)",
      dateLabel: "তারিখ",
      date: "শনিবার, ৬ই ডিসেম্বর, ২০২৫",
      timeLabel: "সময়",
      time: "সকাল ১০:০০ - রাত ৯:০০",
      venueLabel: "স্থান",
      venue: "'আলো ঘর', উত্তরপাড়া, পশ্চিমবঙ্গ, ভারত",
    },
    registrationForm: {
      title: "পুনর্মিলনের জন্য নিবন্ধন করুন",
      description: "আপনার স্থান নিশ্চিত করুন এবং আপনার টি-শার্টের সাইজ জানান!",
      nameLabel: "পুরো নাম",
      namePlaceholder: "যেমনঃ জন ডো",
      phoneLabel: "ফোন নম্বর",
      phonePlaceholder: "যেমনঃ +৮৮০১২৩৪৫৬৭৮৯০",
      tshirtLabel: "টি-শার্ট সাইজ",
      tshirtPlaceholder: "আপনার টি-শার্ট সাইজ নির্বাচন করুন",
      submitButton: "এখন নিবন্ধন করুন",
      submittingButton: "জমা দেওয়া হচ্ছে...",
      successToastTitle: "নিবন্ধন সফল!",
      failureToastTitle: "নিবন্ধন ব্যর্থ",
      errorToastTitle: "ত্রুটি",
      errorToastDescription: "কিছু একটা সমস্যা হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    },
    icebreakerTool: {
      title: "পরিচিতি পর্ব",
      description: "কথাবার্তা শুরু করতে চান? একটি ব্যক্তিগতকৃত প্রশ্ন পেতে কিছু (কাল্পনিক বা আসল) বিবরণ লিখুন!",
      nameLabel: "অংশগ্রহণকারীর নাম",
      namePlaceholder: "যেমনঃ আকাশ সেন",
      phoneLabel: "অংশগ্রহণকারীর ফোন (ঐচ্ছিক)",
      phonePlaceholder: "যেমনঃ +৮৮০১২৩৪৫৬৭৮৯০",
      tshirtLabel: "অংশগ্রহণকারীর টি-শার্ট সাইজ",
      tshirtPlaceholder: "টি-শার্ট সাইজ নির্বাচন করুন",
      submitButton: "আলোচনা শুরু করার প্রশ্ন পান",
      submittingButton: "তৈরি হচ্ছে...",
      suggestionTitle: "আপনার জন্য প্রশ্ন:",
      successToastTitle: "প্রশ্ন তৈরি!",
      successToastDescription: "কথাবার্তা শুরু করার জন্য এখানে একটি মজার প্রশ্ন রয়েছে।",
      failureToastTitle: "তৈরি করতে ব্যর্থ",
      failureToastDescription: "একটি প্রশ্ন তৈরি করা যায়নি।",
      errorToastTitle: "ত্রুটি",
      errorToastDescription: "কিছু একটা সমস্যা হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    },
    faq: {
      title: "সচরাচর জিজ্ঞাসিত প্রশ্ন",
      description: "পুনর্মিলন সম্পর্কিত সাধারণ প্রশ্নের উত্তর খুঁজুন।",
      faqs: [
        {
          id: "faq-1",
          question: "পুনর্মিলনের জন্য পোশাক বিধি কী?",
          answer: "পোশাক বিধি হলো স্মার্ট ক্যাজুয়াল। আনন্দ এবং পুনর্মিলনের একটি দিনের জন্য আরামে এবং স্টাইলিশভাবে পোশাক পরতে পারেন!",
        },
        {
          id: "faq-2",
          question: "আমি কি পুনর্মিলনীতে অতিথি আনতে পারি?",
          answer: "স্থানের সীমাবদ্ধতা এবং পরিকল্পনার কারণে, নিবন্ধন প্রাথমিকভাবে প্রাক্তন ছাত্রদের জন্য। আপনি যদি অতিথি আনতে চান, অনুগ্রহ করে উপলব্ধতা জানতে আয়োজকদের সাথে আগে থেকে যোগাযোগ করুন।",
        },
        {
          id: "faq-3",
          question: "অনুষ্ঠানস্থলে কি পার্কিংয়ের ব্যবস্থা আছে?",
          answer: "'আলো ঘর'-এ সীমিত পার্কিং উপলব্ধ। যানজট কমাতে আমরা সম্ভব হলে কারপুলিং বা গণপরিবহন ব্যবহারের জন্য উৎসাহিত করি।",
        },
        {
          id: "faq-4",
          question: "কোভিড-১৯ নিরাপত্তা প্রোটোকলগুলি কী কী?",
          answer: "অনুষ্ঠানের সময়কার সমস্ত স্থানীয় স্বাস্থ্য নির্দেশিকা এবং পরামর্শ আমরা মেনে চলব। আমরা বিনীতভাবে অনুরোধ করছি যে আপনি যদি অসুস্থ বোধ করেন, অনুগ্রহ করে সকলের নিরাপত্তা নিশ্চিত করতে বাড়িতে থাকুন। হ্যান্ড স্যানিটাইজার উপলব্ধ থাকবে।",
        },
        {
          id: "faq-5",
          question: "খাবার ও পানীয় কি সরবরাহ করা হবে?",
          answer: "হ্যাঁ! সকাল ১০টা থেকে রাত ৯টা পর্যন্ত অনুষ্ঠান জুড়ে বিভিন্ন ধরনের সুস্বাদু খাবার এবং সতেজ পানীয় সরবরাহ করা হবে। আমাদের বিভিন্ন স্বাদের জন্য বিকল্প থাকবে।",
        },
      ],
    },
    footer: {
      copyright: `&copy; ${new Date().getFullYear()} পুনর্মিলন কেন্দ্র। সর্বস্বত্ব সংরক্ষিত।`,
      closing: "তোমাদের সাথে উদযাপন করার জন্য উন্মুখ!",
    },
  },
};
